# Generated by Django 4.0.4 on 2022-11-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
