# Generated by Django 4.0.4 on 2022-11-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150)),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSuper.user')),
            ],
        ),
    ]
