# Generated by Django 4.0.4 on 2022-11-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0002_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
