# Generated by Django 4.0.4 on 2022-11-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0002_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='Mensaje',
            new_name='usuario',
        ),
    ]
