# Generated by Django 4.0.4 on 2022-11-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0005_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
