# Generated by Django 4.0.4 on 2022-11-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0006_remove_mensaje_usuario_mensaje_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
